import { FieldDefinition } from './template.entity';
import { Frequency } from '../../common/enums/frequency.enum';

export interface TemplateSeedData {
  name: string;
  description: string;
  frequency: Frequency;
  fields: FieldDefinition[];
}

export const HACCP_TEMPLATES: TemplateSeedData[] = [
  {
    name: 'Lager & Kühltemperaturen',
    description: 'Tägliche Kontrolle der Lager- und Kühltemperaturen aller Kühlbereiche',
    frequency: Frequency.DAILY,
    fields: [
      {
        key: 'kuehlraum_temp',
        label: 'Kühlraum Temperatur (°C)',
        type: 'number',
        required: true,
        unit: '°C',
        min: -5,
        max: 10,
        criticalMax: 8,
        hint: 'Sollwert: 0–4°C. Kritisch ab 8°C',
      },
      {
        key: 'tiefkuehlraum_temp',
        label: 'Tiefkühlraum Temperatur (°C)',
        type: 'number',
        required: true,
        unit: '°C',
        min: -30,
        max: -10,
        criticalMax: -15,
        hint: 'Sollwert: -18°C oder kälter. Kritisch ab -15°C',
      },
      {
        key: 'kuehlvitrine_temp',
        label: 'Kühlvitrine Temperatur (°C)',
        type: 'number',
        required: true,
        unit: '°C',
        min: 0,
        max: 12,
        criticalMax: 8,
        hint: 'Sollwert: 0–7°C. Kritisch ab 8°C',
      },
      {
        key: 'getraenke_kuehlschrank_temp',
        label: 'Getränke-Kühlschrank Temperatur (°C)',
        type: 'number',
        required: false,
        unit: '°C',
        min: 0,
        max: 15,
        criticalMax: 12,
      },
      {
        key: 'auffaelligkeiten',
        label: 'Auffälligkeiten / Abweichungen',
        type: 'text',
        required: false,
        hint: 'Z.B. Eis-Ansammlungen, defekte Dichtungen, ungewöhnliche Geräusche',
      },
      {
        key: 'korrekturmassnahme',
        label: 'Korrekturmaßnahme eingeleitet',
        type: 'boolean',
        required: false,
      },
    ],
  },
  {
    name: 'Wareneingangskontrolle',
    description: 'Kontrolle bei jeder Warenanlieferung: Temperatur, Zustand, MHD',
    frequency: Frequency.PER_DELIVERY,
    fields: [
      {
        key: 'lieferant',
        label: 'Lieferant',
        type: 'text',
        required: true,
        hint: 'Name des Lieferanten',
      },
      {
        key: 'warengruppe',
        label: 'Warengruppe',
        type: 'select',
        required: true,
        options: ['Fleisch/Geflügel', 'Fisch/Meeresfrüchte', 'Molkereiprodukte', 'Obst/Gemüse', 'Tiefkühlware', 'Trockenwaren', 'Sonstiges'],
      },
      {
        key: 'liefertemperatur',
        label: 'Liefertemperatur (°C)',
        type: 'number',
        required: true,
        unit: '°C',
        min: -25,
        max: 30,
        criticalMax: 8,
        hint: 'Kühlware: max. 7°C, Tiefkühlware: max. -15°C',
      },
      {
        key: 'mhd_ok',
        label: 'MHD / Haltbarkeit in Ordnung',
        type: 'boolean',
        required: true,
      },
      {
        key: 'verpackung_ok',
        label: 'Verpackung unbeschädigt',
        type: 'boolean',
        required: true,
      },
      {
        key: 'geruch_ok',
        label: 'Geruch einwandfrei',
        type: 'boolean',
        required: true,
      },
      {
        key: 'farbe_konsistenz_ok',
        label: 'Farbe und Konsistenz einwandfrei',
        type: 'boolean',
        required: true,
      },
      {
        key: 'ware_angenommen',
        label: 'Ware angenommen',
        type: 'boolean',
        required: true,
      },
      {
        key: 'bemerkungen',
        label: 'Bemerkungen / Beanstandungen',
        type: 'text',
        required: false,
      },
    ],
  },
  {
    name: 'Erhitzungstemperatur',
    description: 'Stichprobenkontrolle der Kerntemperatur beim Erhitzen/Garen',
    frequency: Frequency.SPOT_CHECK,
    fields: [
      {
        key: 'speise',
        label: 'Speise / Produkt',
        type: 'text',
        required: true,
        hint: 'Welches Gericht oder Produkt wurde kontrolliert?',
      },
      {
        key: 'kerntemperatur',
        label: 'Kerntemperatur (°C)',
        type: 'number',
        required: true,
        unit: '°C',
        min: 40,
        max: 120,
        criticalMin: 70,
        hint: 'Mindest-Kerntemperatur: 70°C (2 Min.) oder 80°C (Geflügel)',
      },
      {
        key: 'erhitzungsdauer_min',
        label: 'Erhitzungsdauer (Minuten)',
        type: 'number',
        required: false,
        unit: 'min',
        min: 0,
        max: 120,
      },
      {
        key: 'thermometer_id',
        label: 'Thermometer-ID / Gerät',
        type: 'text',
        required: false,
      },
      {
        key: 'anforderung_erfuellt',
        label: 'Temperaturanforderung erfüllt',
        type: 'boolean',
        required: true,
      },
      {
        key: 'massnahme_bei_abweichung',
        label: 'Maßnahme bei Abweichung',
        type: 'text',
        required: false,
        hint: 'Z.B. Weitererhitzen, Vernichtung',
      },
    ],
  },
  {
    name: 'Ausgabetemperatur',
    description: 'Stichprobenkontrolle der Temperatur bei der Speiseausgabe',
    frequency: Frequency.SPOT_CHECK,
    fields: [
      {
        key: 'speise',
        label: 'Speise / Gericht',
        type: 'text',
        required: true,
      },
      {
        key: 'ausgabe_temperatur',
        label: 'Ausgabetemperatur (°C)',
        type: 'number',
        required: true,
        unit: '°C',
        min: -5,
        max: 100,
        criticalMin: 65,
        hint: 'Warmspeisen: min. 65°C. Kaltspeisen: max. 7°C',
      },
      {
        key: 'ausgabe_typ',
        label: 'Art der Ausgabe',
        type: 'select',
        required: true,
        options: ['Warmspeise', 'Kaltspeise', 'Buffet warm', 'Buffet kalt'],
      },
      {
        key: 'ausgabezeit',
        label: 'Ausgabezeitpunkt',
        type: 'text',
        required: false,
        hint: 'Uhrzeit der Kontrolle',
      },
      {
        key: 'anforderung_erfuellt',
        label: 'Temperaturanforderung erfüllt',
        type: 'boolean',
        required: true,
      },
      {
        key: 'bemerkungen',
        label: 'Bemerkungen',
        type: 'text',
        required: false,
      },
    ],
  },
  {
    name: 'Reinigung & Desinfektion',
    description: 'Tägliche Dokumentation der Reinigungs- und Desinfektionsmaßnahmen',
    frequency: Frequency.DAILY,
    fields: [
      {
        key: 'kueche_gereinigt',
        label: 'Küche gereinigt und desinfiziert',
        type: 'boolean',
        required: true,
      },
      {
        key: 'arbeitsflächen_gereinigt',
        label: 'Arbeitsflächen gereinigt',
        type: 'boolean',
        required: true,
      },
      {
        key: 'schneidbretter_gereinigt',
        label: 'Schneidbretter gereinigt und desinfiziert',
        type: 'boolean',
        required: true,
      },
      {
        key: 'geraete_gereinigt',
        label: 'Geräte und Maschinen gereinigt',
        type: 'boolean',
        required: true,
      },
      {
        key: 'boden_gereinigt',
        label: 'Böden gereinigt',
        type: 'boolean',
        required: true,
      },
      {
        key: 'abfall_entsorgt',
        label: 'Abfall fachgerecht entsorgt',
        type: 'boolean',
        required: true,
      },
      {
        key: 'reinigungsmittel',
        label: 'Verwendetes Reinigungsmittel',
        type: 'text',
        required: false,
        hint: 'Name und Konzentration des Reinigungs-/Desinfektionsmittels',
      },
      {
        key: 'desinfektionsmittel',
        label: 'Verwendetes Desinfektionsmittel',
        type: 'text',
        required: false,
      },
      {
        key: 'auffaelligkeiten',
        label: 'Auffälligkeiten / Mängel',
        type: 'text',
        required: false,
      },
    ],
  },
  {
    name: 'Schädlingsbekämpfung',
    description: 'Zweiwöchentliche Kontrolle auf Schädlingsbefall',
    frequency: Frequency.TWICE_MONTHLY,
    fields: [
      {
        key: 'insekten_befall',
        label: 'Insektenbefall festgestellt',
        type: 'boolean',
        required: true,
      },
      {
        key: 'nagetier_befall',
        label: 'Nagetierbefall festgestellt (Kot, Fraßspuren)',
        type: 'boolean',
        required: true,
      },
      {
        key: 'fallen_kontrolliert',
        label: 'Fallen/Monitore kontrolliert',
        type: 'boolean',
        required: true,
      },
      {
        key: 'anzahl_fallen',
        label: 'Anzahl kontrollierter Fallen',
        type: 'number',
        required: false,
        unit: 'Stück',
        min: 0,
        max: 100,
      },
      {
        key: 'befallsort',
        label: 'Befallsort (falls zutreffend)',
        type: 'text',
        required: false,
      },
      {
        key: 'massnahmen_eingeleitet',
        label: 'Bekämpfungsmaßnahmen eingeleitet',
        type: 'boolean',
        required: false,
      },
      {
        key: 'externen_schaedlingsbekaempfer_informiert',
        label: 'Externen Schädlingsbekämpfer informiert',
        type: 'boolean',
        required: false,
      },
      {
        key: 'bemerkungen',
        label: 'Bemerkungen / Details',
        type: 'text',
        required: false,
      },
    ],
  },
  {
    name: 'Personalschulung',
    description: 'Jährliche Dokumentation der Hygieneschulung für Mitarbeiter',
    frequency: Frequency.YEARLY,
    fields: [
      {
        key: 'schulungsthema',
        label: 'Schulungsthema',
        type: 'select',
        required: true,
        options: [
          'Lebensmittelhygiene (Grundschulung)',
          'HACCP-Konzept',
          'Persönliche Hygiene',
          'Allergene',
          'Schädlingsprävention',
          'Reinigung und Desinfektion',
          'Auffrischungsschulung',
          'Sonstiges',
        ],
      },
      {
        key: 'schulungsart',
        label: 'Art der Schulung',
        type: 'select',
        required: true,
        options: ['Interne Schulung', 'Externe Schulung', 'Online-Schulung', 'Unterweisung am Arbeitsplatz'],
      },
      {
        key: 'teilnehmer_anzahl',
        label: 'Anzahl Teilnehmer',
        type: 'number',
        required: true,
        unit: 'Personen',
        min: 1,
        max: 200,
      },
      {
        key: 'schulungsdauer_stunden',
        label: 'Schulungsdauer (Stunden)',
        type: 'number',
        required: true,
        unit: 'h',
        min: 0.5,
        max: 40,
      },
      {
        key: 'referent',
        label: 'Referent / Schulungsleiter',
        type: 'text',
        required: true,
      },
      {
        key: 'nachweis_vorhanden',
        label: 'Schulungsnachweis vorhanden',
        type: 'boolean',
        required: true,
      },
      {
        key: 'naechste_schulung',
        label: 'Nächste Schulung geplant für',
        type: 'text',
        required: false,
        hint: 'Datum der nächsten Schulung (YYYY-MM-DD)',
      },
      {
        key: 'bemerkungen',
        label: 'Bemerkungen / Inhalte',
        type: 'text',
        required: false,
      },
    ],
  },
];
